---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: discord-forecast-secret
  namespace: forecast
spec:
  encryptedData:
    DISCORD_FORECAST_BOT_TOKEN: AgBYVxOnU34GFOIdjq4p0DokAig2UbAcKVNASP6+ukuIigIC4V9xfTWDlvcIOHCYIszlZAAFJAjOS1juv/A4x4hQ1KyUeAN8VG8K7jda7KVKk1UuX2QMayNwVTlAVqn2BfH4KweBCvnGcsLUxOtOdyEWjpj4dXXt6YWLm2kHQPNRBKNqZnCnsDD68lVZgKPxxaDW/xeEiU7Q1cGbaGMX5trr6958+lm8l4OJatV0D0YQWj9OHV01MqE9QR7kOPHU5u752W2KZHOXHhCxpMZgfb1aHPX3dvr6/4NKCb4TTIrza30YKqSG0XC0dhEfPAki2rtRHnKzytndpYTKjdm1sZOACF6E5NQjb5iIquO4FsBWMRPL6TfCxunVOx0cwy6zvLRtpCITyNbRwsjaocjajeHFyXwRnG2RiRFlG/CTFy3L2VDieq2FzUpka+ZNRCDDQPITilq2edYWJF8II7RQg1RKA0bM0zAyDq2bcfrzWxKAPlNOX/i8B0Kct1dRdHLzcsPlrgpYHWNQsyrC4VnK6MX6MncL0wr/kuYMKmFPP0SVlQxuNDC7R92vhzjkpdJo2tlAx1+6J9YbjwXdtm0Eo3gf0eaJF/H33zU9bEzq/l9CzE/qypVagMGEuljVG4pGInYTtowMOtVIw22dJb0odHycVi4PPv3rTsI2xtm5HVtfw6/yLTAtM/7J5iGVeoVy1ZO56ywDb0ju+Zbm47FjsqRLztIZLpUOFr4PEhpm19mYgCZ1DW8yM5xZaYeqNqYwLmr0lnT0SSdS81wKKvi96DmMfUWw6ojXbEE=
    DISCORD_FORECAST_CHANNEL_ID: AgCg7zhXXjX4bIZdK4Pu7kl2DxwSwpfnBKdMW7KxWBRwzByCRRaRoa5a92+fbswLmJSWlO4j7FsEcQWrgGplCm2fctTJjzvy8Zj8Z2+0qzS1oLWZqkp37eOCiLv8CHH6LUqqMRr/3CPJolOIjoO6gK3QlQDlEmuFM7pnAbPFjhZNxcJQ2q6iQHIwjCXPAcJgFJel9jwhVXAuyYa0g/61lh7DXUlWw3ePVRNq0TM7TDNGBDBI+yx1xl9SvW2wSyHGuXhb7f/ZkMpPeudbioL2I9jPT40pAVqidjkPe2qqGsd0mhDBE3iDWIJR03tsi7ykIc+0537YBLU+D/PmMQF80lugPHILalTkXyGEhx6txrXFR1o8AH4xd8sS81AKFrLmUzvLG6xs2+X/hvuczv40tjMGdIi7EzU1teg2uu+ySf0G05cqv7A7Y+y4kKAdYKLIsO+eKLM7Fy6we9FLuApS6OIEPnHa1t6SLPNvnBub+jJWgJKPu+bPR08w7k4fw7lMeWioZxFlCCBB91kwNwUOC6u3KKNzS93g1qiEuj2+U8AapjSpIZHb/zphHAmT5I5txg2INled1xhqozkcTFQJw6TlRy+C6wT23r1S+3hQhIFsskbA2yfOF8BxqXiFcJ16OYyYJoA1f8dVWm4GPqWxFczaauhYkOszdZ4pn6/IH4WeY0bb+DIcsvhNb5PjAfvMOKAxwNlKhGXIFwGHVc1bc3o+zQU8
  template:
    metadata:
      creationTimestamp: null
      name: discord-forecast-secret
      namespace: forecast
