---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: discord-forecast-secret
  namespace: default
spec:
  encryptedData:
    DISCORD_FORECAST_BOT_TOKEN: AgABayv6Tqz2rVppcRIHuuoECdWh0xjPf+Wax3OgyyqRtvq0gTTis+T7tMQTpAFhWGEu+29zHgQwqOvDzZo9mLGJB+L6LQoqLe2Yw8z/EiLph8oANdauwWPsjUkkTQdSq7umv08zjxm1Dd667v6BICcz/MSNdmEwhXJaIam+3x92S9+tMHuWG5GagXFHksn5fSmDPGGRgK+KmPZNU1rMDX+WWl1Chi25wwZfurhhLYX3AlPMMQTJ2U/fzLK5B2LdfEeB160SmR+O+BVZMC6mXs/7YLQBEpLDL1a9cX+/Qr7GMUfwzNtAqzBGJ1kcFAvKABWWWXkaNvtrppVvsS75HUAly4lNOh2sXFTwyntgGZlQevtzpHCOnY5Zg368hmZ75UvwdLBxZ9liWt82EgWSuyAsZORsAwRD2F8n7UIPhnQ2EFWr2BDKhuXy/yFmRdMSxd9OiYW0CDuhEQi2I+qjs4VWcqAuMheHXpdGhf4f1pITJDcQkHoy/od/3s/2KDHLH8Sf2JzF+UYDypP+sK6Alau20uYHMUoljdWuAFASeoDug1/21/0Bsoywu92B09wCSkueTsg/z/uXMLJJtI9Cf9HdzdEfslO2QlUnTFFv/RWpgus/tezbkFcP0K1jIcYjfy6eqh3GU4s5A1sACLZSwUL6S3bnv2R0VzD/SjyMKIAZULAhbWPsXIyuF1yAQP+p/YNwLg5E91cJa+9Z2ykBGVIyXQvZIDnocaYaY6XnJil+ICZqD89F0oEHGmJT8XJVnCRPfsW6LD9gcQK48daE8F/56Y1YmvoERTc=
    DISCORD_FORECAST_CHANNEL_ID: AgB9C72nCS8/OpgXkv8F8ggO/OI/S8rUUmsksVnT7I3h9YLkPHJ0RVjJr7lG3PSUrHo8P142RdCz7Lew66/dWYcgpHbn3BKD6por/lGH2nGbkXE6QuzKTevHIVaWtNzDdzjZd+C41uouyjksBQlvaVXVT7Nsw18UVInkcVSKccAA+Uoae6+MPem2MnzbbqZOGtEEL/tIh7y7tCXOcEbVTrPELGWOE0koasL9FVTdmfDJRtCbDxzYDVmz+QDwA/Ol/1b5TgphlnouIZeg8WBG5l2iNA6wGbs91qWOpAdSopXuySZWkl3ojGEv3kG70LQwmq9MrVg1Ela8cZwtgMJuXyYWcYCjNnZkrfRaYtxQYfpthJQh/jSEl2RwjCG2Jre6vN1jZsmXd6WDdFCTz0w/unlxOiUYgSFqeId//AY4QIkU2+F+ZKAFVlpmP9Jzn8defwN7covbzP0TI0qJzAaqpZ+CofqVrjllyqg/UcNoNoMn3eM5SUpe6R7IJ3OFXM1zDj2+z9pIC0Uqj77NoFP6/ocsfdHYsY3Y0wi/Fit7Lb1YXxE+I/9IEJvVmHjRq7k11XbZ8/F9wCsA68RuKag8nXIR9ZisVE3aXf8tm9zEyd8VOI1H8N1tsJjRvCo03k0ZSfPfz//IMa68iHE8x4JeNFchD6PcxV/jgC9LGCS4jAE3bK+SRnZo+yEsooU1VK6u8jl040mNwrqHEEoYurlTNkj4I2fQ
  template:
    metadata:
      creationTimestamp: null
      name: discord-forecast-secret
      namespace: default
